services:
# Redis Cache
  redis:
    image: redis:6-alpine
    container_name: shareascan-api-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - shareascan-api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel API with PHP-FPM and Nginx
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shareascan-api-app
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost:3390}
      DATABASE_URL: "postgresql://neondb_owner:npg_EkUg1tQ0yexZ@ep-cool-king-ae4ubrz2-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
      - ./.env.docker:/var/www/html/.env:ro
    ports:
      - "${API_PORT:-3390}:80"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - shareascan-api-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shareascan-api-queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DB_CONNECTION: pgsql
      DB_HOST: ep-cool-king-ae4ubrz2-pooler.c-2.us-east-2.aws.neon.tech
      DB_PORT: 5432
      DB_DATABASE: neondb
      DB_USERNAME: neondb_owner
      DB_PASSWORD: "npg_EkUg1tQ0yexZ@"
      DB_SSLMODE: require
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env.docker:/var/www/html/.env:ro
    depends_on:
      - api
    networks:
      - shareascan-api-network

networks:
  shareascan-api-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
